"""
Subject registry — single source of truth for what subjects exist and how
each one differs (URL prefix, template, whether it has a section report, etc.).

Adding a new subject = adding ~10 lines here. No more 16 copies of routes.py.
"""

from config import (
    INFORMATICS_SUBJECT_ID,
    MATH_SUBJECT_ID,
    GEOMETRY_SUBJECT_ID,
    MS_SUBJECT_ID,
    PHYSICS_SUBJECT_ID,
    CHEMISTRY_SUBJECT_ID,
    KUKYK_SUBJECT_ID,
    GEOGRAPHY_SUBJECT_ID,
    HISTORY_SUBJECT_ID,
    WORLD_HISTORY_SUBJECT_ID,
    BIOLOGY_SUBJECT_ID,
    KAZAKH_LANGUAGE_SUBJECT_ID,
    KAZAKH_LITERATURE_SUBJECT_ID,
    RUSSIAN_LANGUAGE_SUBJECT_ID,
    RUSSIAN_LITERATURE_SUBJECT_ID,
    ENGLISH_SUBJECT_ID,
)
from subjects._factory import SubjectConfig


# Order matters only for the dashboard tab list (which is currently in the
# template, not derived from here, but keep the same order for sanity).
SUBJECTS: list[SubjectConfig] = [
    # ── Есеп пәндер ─────────────────────────────────────────────────────────
    SubjectConfig(
        slug="informatics",
        name="Информатика",
        subject_id=INFORMATICS_SUBJECT_ID,
        prefix="",                     # informatics is the root — no /informatics prefix
        active_subject="informatics",
        report_template="report.html",
        metrics_module="subjects.informatics.metrics",
        builder_module="subjects.informatics.builder",
        has_debug_themes=True,         # informatics-only debug endpoint
    ),
    SubjectConfig(
        slug="math",
        name="Математика",
        subject_id=MATH_SUBJECT_ID,
        prefix="/math",
        active_subject="math",
        report_template="report.html",                 # uses the generic template
        metrics_module="subjects.math.metrics",
        builder_module="subjects.math.builder",
    ),
    SubjectConfig(
        slug="geometry",
        name="Геометрия",
        subject_id=GEOMETRY_SUBJECT_ID,
        prefix="/geometry",
        active_subject="geometry",
        report_template="report.html",                 # uses the generic template
        metrics_module="subjects.geometry.metrics",
        builder_module="subjects.geometry.builder",
    ),
    SubjectConfig(
        slug="ms",
        name="Математикалық сауаттылық",
        subject_id=MS_SUBJECT_ID,
        prefix="/ms",
        active_subject="ms",
        report_template="report.html",                 # uses the generic template
        metrics_module="subjects.ms.metrics",
        builder_module="subjects.ms.builder",
    ),
    SubjectConfig(
        slug="physics",
        name="Физика",
        subject_id=PHYSICS_SUBJECT_ID,
        prefix="/physics",
        active_subject="physics",
        report_template="physics_report.html",         # legacy naming, prefix-suffix swap
        metrics_module="subjects.physics.metrics",
        builder_module="subjects.physics.builder",
    ),
    SubjectConfig(
        slug="chemistry",
        name="Химия",
        subject_id=CHEMISTRY_SUBJECT_ID,
        prefix="/chemistry",
        active_subject="chemistry",
        report_template="chemistry_report.html",       # legacy naming, prefix-suffix swap
        metrics_module="subjects.chemistry.metrics",
        builder_module="subjects.chemistry.builder",
    ),

    # ── Ауызша пәндер ───────────────────────────────────────────────────────
    SubjectConfig(
        slug="geography",
        name="География",
        subject_id=GEOGRAPHY_SUBJECT_ID,
        prefix="/geography",
        active_subject="geography",
        report_template="report_geography.html",
        metrics_module="subjects.geography.metrics",
        builder_module="subjects.geography.builder",
        use_paginated_fetch=True,
        pass_stream_month=True,
        has_section_report=True,
        csv_filename="geography_report.csv",
    ),
    SubjectConfig(
        slug="kukyk",
        name="Құқық негіздері",
        subject_id=KUKYK_SUBJECT_ID,
        prefix="/kukyk",
        active_subject="kukyk",
        report_template="report_kukyk.html",
        metrics_module="subjects.kukyk.metrics",
        builder_module="subjects.kukyk.builder",
        use_paginated_fetch=True,
        pass_stream_month=True,
        csv_filename="kukyk_report.csv",
    ),
    SubjectConfig(
        slug="history",
        name="Қазақстан тарихы",
        subject_id=HISTORY_SUBJECT_ID,
        prefix="/history",
        active_subject="history",
        report_template="report_history.html",
        metrics_module="subjects.history.metrics",
        builder_module="subjects.history.builder",
        use_paginated_fetch=True,
        pass_stream_month=True,
        has_section_report=True,
        csv_filename="history_report.csv",
    ),
    SubjectConfig(
        slug="world-history",
        name="Дүниежүзі тарихы",
        subject_id=WORLD_HISTORY_SUBJECT_ID,
        prefix="/world-history",
        active_subject="world_history",
        report_template="report_geography.html",       # reuses geography's template (intentional)
        metrics_module="subjects.world_history.metrics",
        builder_module="subjects.world_history.builder",
        use_paginated_fetch=True,
        pass_stream_month=True,
        has_section_report=True,
        csv_filename="world_history_report.csv",
    ),
    SubjectConfig(
        slug="biology",
        name="Биология",
        subject_id=BIOLOGY_SUBJECT_ID,
        prefix="/biology",
        active_subject="biology",
        report_template="report_biology.html",
        metrics_module="subjects.biology.metrics",
        builder_module="subjects.biology.builder",
        use_paginated_fetch=True,
        pass_stream_month=True,
        has_section_report=True,
        csv_filename="biology_report.csv",
    ),
    SubjectConfig(
        slug="kazakh-language",
        name="Қазақ тілі",
        subject_id=KAZAKH_LANGUAGE_SUBJECT_ID,
        prefix="/kazakh-language",
        active_subject="kazakh-language",
        report_template="report_kazakh_language.html",
        metrics_module="subjects.kazakh_language.metrics",
        builder_module="subjects.kazakh_language.builder",
        use_paginated_fetch=True,
        pass_stream_month=True,
        has_section_report=True,
        csv_filename="kazakh_language_report.csv",
    ),
    SubjectConfig(
        slug="kazakh-literature",
        name="Қазақ әдебиеті",
        subject_id=KAZAKH_LITERATURE_SUBJECT_ID,
        prefix="/kazakh-literature",
        active_subject="kazakh_literature",
        report_template="report_kazakh_literature.html",
        metrics_module="subjects.kazakh_literature.metrics",
        builder_module="subjects.kazakh_literature.builder",
        use_paginated_fetch=True,
        pass_stream_month=True,
        has_section_report=True,
        csv_filename="kazakh_literature_report.csv",
    ),
    SubjectConfig(
        slug="russian-language",
        name="Орыс тілі",
        subject_id=RUSSIAN_LANGUAGE_SUBJECT_ID,
        prefix="/russian-language",
        active_subject="russian_language",
        report_template="report_russian_language.html",
        metrics_module="subjects.russian_language.metrics",
        builder_module="subjects.russian_language.builder",
        use_paginated_fetch=True,
        pass_stream_month=True,
        has_section_report=True,
        csv_filename="russian_language_report.csv",
    ),
    SubjectConfig(
        slug="russian-literature",
        name="Орыс әдебиеті",
        subject_id=RUSSIAN_LITERATURE_SUBJECT_ID,
        prefix="/russian-literature",
        active_subject="russian_literature",
        report_template="report_russian_literature.html",
        metrics_module="subjects.russian_literature.metrics",
        builder_module="subjects.russian_literature.builder",
        use_paginated_fetch=True,
        pass_stream_month=True,
        csv_filename="russian_literature_report.csv",
    ),
    SubjectConfig(
        slug="english",
        name="Ағылшын тілі",
        subject_id=ENGLISH_SUBJECT_ID,
        prefix="/english",
        active_subject="english",
        report_template="report_english.html",
        metrics_module="subjects.english.metrics",
        builder_module="subjects.english.builder",
        use_paginated_fetch=True,
        pass_stream_month=True,
        csv_filename="english_report.csv",
    ),
]
